/**
 * Export Manager for Isometric 3D Editor
 *
 * Stage 1 fixes:
 *   - OBJ export now traverses THREE.Group objects (buildings, stairs, bridges)
 *     instead of crashing on undefined .geometry
 *   - STL (ASCII + binary) has the same Group traversal fix
 *   - Unity tilemap JSON now includes shadowCasting + receiveShadows per tile
 *   - Unity C# importer sets shadow flags and emits a pre-configured
 *     DirectionalLight GameObject for real-time shadows
 */

class ExportManager {
    constructor(scene, objects, layerManager, textureManager) {
        this.scene        = scene;
        this.objects      = objects;
        this.layerManager = layerManager;
        this.textureManager = textureManager;
    }

    /* ------------------------------------------------------------------ */
    /*  HELPERS                                                             */
    /* ------------------------------------------------------------------ */

    /**
     * Collect all renderable {geometry, matrixWorld, material} from an object.
     * Works for plain Mesh and for THREE.Group (buildings, stairs, bridges).
     *
     * @param {THREE.Object3D} obj
     * @returns {Array<{geometry, matrixWorld, material}>}
     */
    _collectMeshes(obj) {
        const meshes = [];

        if (obj.isMesh) {
            meshes.push({
                geometry:   obj.geometry,
                matrixWorld: obj.matrixWorld,
                material:   obj.material
            });
        } else if (obj.isGroup) {
            obj.updateMatrixWorld(true);
            obj.traverse(child => {
                if (child.isMesh) {
                    meshes.push({
                        geometry:   child.geometry,
                        matrixWorld: child.matrixWorld,
                        material:   child.material
                    });
                }
            });
        }

        return meshes;
    }

    /**
     * Determine the representative material type / sprite name for export.
     */
    _getSpriteName(obj) {
        if (obj.userData.spriteName)    return obj.userData.spriteName;
        if (obj.userData.materialType)  return obj.userData.materialType;

        // Fallback: inspect geometry type of the object or its first child
        let geomType = null;
        if (obj.isMesh) {
            geomType = obj.geometry && obj.geometry.type;
        } else if (obj.isGroup) {
            const first = obj.children.find(c => c.isMesh);
            geomType = first && first.geometry && first.geometry.type;
        }

        const map = {
            BoxGeometry:      'cube',
            CylinderGeometry: 'cylinder',
            SphereGeometry:   'sphere'
        };
        return (geomType && map[geomType]) || 'default';
    }

    /**
     * Get material colour data.
     * For Groups, reads the first child mesh's material.
     */
    _getMaterialData(obj) {
        let mat = null;
        if (obj.isMesh) {
            mat = obj.material;
        } else if (obj.isGroup) {
            const first = obj.children.find(c => c.isMesh);
            mat = first && first.material;
        }

        if (!mat) return { color: '#ffffff', transparent: false, opacity: 1 };

        return {
            color:       '#' + mat.color.getHexString(),
            transparent: mat.transparent || false,
            opacity:     mat.opacity     || 1.0
        };
    }

    /* ------------------------------------------------------------------ */
    /*  OBJ EXPORT                                                          */
    /* ------------------------------------------------------------------ */

    exportToOBJ(filename) {
        filename = filename || 'scene.obj';
        let objContent = '# Isometric Scene Export\n';
        objContent += '# Generated by Isometric 3D Editor\n';
        objContent += '# Objects: ' + this.objects.length + '\n\n';

        let vertexOffset = 1;

        this.objects.forEach((obj, index) => {
            const name = obj.userData.name || ('object_' + index);
            const meshes = this._collectMeshes(obj);

            meshes.forEach((entry, mi) => {
                const meshName = meshes.length > 1 ? (name + '_part' + mi) : name;
                objContent += '\n# Object: ' + meshName + '\n';
                objContent += 'o ' + meshName + '\n';

                // Clone geometry and apply world transform so export is in world space
                const geometry = entry.geometry.clone();
                geometry.applyMatrix4(entry.matrixWorld);

                const positions  = geometry.attributes.position;
                const uvAttribute = geometry.attributes.uv;

                // Vertices
                for (let i = 0; i < positions.count; i++) {
                    objContent += 'v '
                        + positions.getX(i).toFixed(4) + ' '
                        + positions.getY(i).toFixed(4) + ' '
                        + positions.getZ(i).toFixed(4) + '\n';
                }

                // UVs
                if (uvAttribute) {
                    for (let i = 0; i < uvAttribute.count; i++) {
                        objContent += 'vt '
                            + uvAttribute.getX(i).toFixed(4) + ' '
                            + uvAttribute.getY(i).toFixed(4) + '\n';
                    }
                }

                // Normals
                geometry.computeVertexNormals();
                const normals = geometry.attributes.normal;
                if (normals) {
                    for (let i = 0; i < normals.count; i++) {
                        objContent += 'vn '
                            + normals.getX(i).toFixed(4) + ' '
                            + normals.getY(i).toFixed(4) + ' '
                            + normals.getZ(i).toFixed(4) + '\n';
                    }
                }

                // Faces
                const writeface = (v1, v2, v3) => {
                    if (uvAttribute) {
                        objContent += 'f '
                            + v1 + '/' + v1 + '/' + v1 + ' '
                            + v2 + '/' + v2 + '/' + v2 + ' '
                            + v3 + '/' + v3 + '/' + v3 + '\n';
                    } else {
                        objContent += 'f '
                            + v1 + '//' + v1 + ' '
                            + v2 + '//' + v2 + ' '
                            + v3 + '//' + v3 + '\n';
                    }
                };

                if (geometry.index) {
                    const indices = geometry.index.array;
                    for (let i = 0; i < indices.length; i += 3) {
                        writeface(
                            indices[i]     + vertexOffset,
                            indices[i + 1] + vertexOffset,
                            indices[i + 2] + vertexOffset
                        );
                    }
                } else {
                    for (let i = 0; i < positions.count; i += 3) {
                        writeface(
                            i + vertexOffset,
                            i + vertexOffset + 1,
                            i + vertexOffset + 2
                        );
                    }
                }

                vertexOffset += positions.count;
            });
        });

        this.downloadFile(objContent, filename, 'text/plain');
    }

    /* ------------------------------------------------------------------ */
    /*  STL EXPORT                                                          */
    /* ------------------------------------------------------------------ */

    exportToSTL(filename, binary) {
        if (binary) {
            this._exportBinarySTL(filename || 'scene.stl');
        } else {
            this._exportASCIISTL(filename || 'scene.stl');
        }
    }

    _exportASCIISTL(filename) {
        let stlContent = 'solid IsometricScene\n';

        this.objects.forEach(obj => {
            const meshes = this._collectMeshes(obj);
            meshes.forEach(entry => {
                const geometry = entry.geometry.clone();
                geometry.applyMatrix4(entry.matrixWorld);

                const positions = geometry.attributes.position;
                const indices   = geometry.index ? geometry.index.array : null;

                const writeFacet = (i0, i1, i2) => {
                    const v0 = new THREE.Vector3().fromBufferAttribute(positions, i0);
                    const v1 = new THREE.Vector3().fromBufferAttribute(positions, i1);
                    const v2 = new THREE.Vector3().fromBufferAttribute(positions, i2);
                    const normal = new THREE.Vector3()
                        .subVectors(v1, v0)
                        .cross(new THREE.Vector3().subVectors(v2, v0))
                        .normalize();

                    stlContent += '  facet normal '
                        + normal.x.toFixed(6) + ' '
                        + normal.y.toFixed(6) + ' '
                        + normal.z.toFixed(6) + '\n';
                    stlContent += '    outer loop\n';
                    stlContent += '      vertex ' + v0.x.toFixed(6) + ' ' + v0.y.toFixed(6) + ' ' + v0.z.toFixed(6) + '\n';
                    stlContent += '      vertex ' + v1.x.toFixed(6) + ' ' + v1.y.toFixed(6) + ' ' + v1.z.toFixed(6) + '\n';
                    stlContent += '      vertex ' + v2.x.toFixed(6) + ' ' + v2.y.toFixed(6) + ' ' + v2.z.toFixed(6) + '\n';
                    stlContent += '    endloop\n';
                    stlContent += '  endfacet\n';
                };

                if (indices) {
                    for (let i = 0; i < indices.length; i += 3) {
                        writeFacet(indices[i], indices[i + 1], indices[i + 2]);
                    }
                } else {
                    for (let i = 0; i < positions.count; i += 3) {
                        writeFacet(i, i + 1, i + 2);
                    }
                }
            });
        });

        stlContent += 'endsolid IsometricScene\n';
        this.downloadFile(stlContent, filename, 'text/plain');
    }

    _exportBinarySTL(filename) {
        const triangles = [];

        this.objects.forEach(obj => {
            const meshes = this._collectMeshes(obj);
            meshes.forEach(entry => {
                const geometry = entry.geometry.clone();
                geometry.applyMatrix4(entry.matrixWorld);

                const positions = geometry.attributes.position;
                const indices   = geometry.index ? geometry.index.array : null;

                if (indices) {
                    for (let i = 0; i < indices.length; i += 3) {
                        triangles.push({
                            v0: new THREE.Vector3().fromBufferAttribute(positions, indices[i]),
                            v1: new THREE.Vector3().fromBufferAttribute(positions, indices[i + 1]),
                            v2: new THREE.Vector3().fromBufferAttribute(positions, indices[i + 2])
                        });
                    }
                } else {
                    for (let i = 0; i < positions.count; i += 3) {
                        triangles.push({
                            v0: new THREE.Vector3().fromBufferAttribute(positions, i),
                            v1: new THREE.Vector3().fromBufferAttribute(positions, i + 1),
                            v2: new THREE.Vector3().fromBufferAttribute(positions, i + 2)
                        });
                    }
                }
            });
        });

        const bufferLength = 80 + 4 + triangles.length * 50;
        const buffer       = new ArrayBuffer(bufferLength);
        const view         = new DataView(buffer);

        const header = 'Binary STL from Isometric Editor';
        for (let i = 0; i < 80; i++) {
            view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
        }
        view.setUint32(80, triangles.length, true);

        let offset = 84;
        triangles.forEach(tri => {
            const normal = new THREE.Vector3()
                .subVectors(tri.v1, tri.v0)
                .cross(new THREE.Vector3().subVectors(tri.v2, tri.v0))
                .normalize();

            view.setFloat32(offset, normal.x, true); offset += 4;
            view.setFloat32(offset, normal.y, true); offset += 4;
            view.setFloat32(offset, normal.z, true); offset += 4;

            [tri.v0, tri.v1, tri.v2].forEach(v => {
                view.setFloat32(offset, v.x, true); offset += 4;
                view.setFloat32(offset, v.y, true); offset += 4;
                view.setFloat32(offset, v.z, true); offset += 4;
            });

            view.setUint16(offset, 0, true); offset += 2;
        });

        const blob = new Blob([buffer], { type: 'application/octet-stream' });
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement('a');
        a.href     = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }

    /* ------------------------------------------------------------------ */
    /*  UNITY TILEMAP EXPORT                                                */
    /* ------------------------------------------------------------------ */

    exportToUnityTilemap(options) {
        options = options || {};
        const includeColliders = options.includeColliders !== undefined
            ? options.includeColliders : true;
        const colliderType = options.colliderType || 'box';
        const cellSize     = options.cellSize     || 1;

        const tiles  = [];
        const layers = this.layerManager.getAllLayers();

        layers.forEach(layer => {
            layer.objects.forEach(obj => {
                const gridX = Math.round(obj.position.x / cellSize);
                const gridY = Math.round(obj.position.z / cellSize);

                // Bounding box works for both Mesh and Group
                const box = new THREE.Box3().setFromObject(obj);
                const size = new THREE.Vector3();
                box.getSize(size);

                const tile = {
                    gridX:    gridX,
                    gridY:    gridY,
                    worldY:   obj.position.y,          // vertical position (layer height)
                    name:     obj.userData.name  || 'Tile',
                    type:     obj.userData.type  || 'cube',
                    layer:    layer.name,
                    zIndex:   obj.userData.zindex || 0,
                    rotation: Math.round(obj.rotation.y * 180 / Math.PI / 90) * 90,
                    scale: {
                        x: Math.round(obj.scale.x * 100) / 100,
                        y: Math.round(obj.scale.y * 100) / 100,
                        z: Math.round(obj.scale.z * 100) / 100
                    },
                    spriteName: this._getSpriteName(obj),
                    material:   this._getMaterialData(obj),
                    bounds: {
                        width:  Math.round(size.x * 100) / 100,
                        height: Math.round(size.y * 100) / 100,
                        depth:  Math.round(size.z * 100) / 100
                    },
                    // Stage-1 addition: shadow flags for Unity
                    shadowCasting:  'TwoSided',
                    receiveShadows: true
                };

                if (includeColliders) {
                    tile.collider = {
                        enabled: true,
                        type:    colliderType,
                        size:    [tile.bounds.width, tile.bounds.height, tile.bounds.depth]
                    };
                }

                tiles.push(tile);
            });
        });

        const exportData = {
            version: '1.1',
            format:  'isometric_tilemap',
            settings: {
                cellSize:       { x: cellSize, y: cellSize, z: cellSize },
                gridOrientation: 'isometric',
                hasColliders:    includeColliders,
                colliderType:    colliderType,
                shadowsEnabled:  true
            },
            layers: layers.map(l => ({ id: l.id, name: l.name })),
            tiles:  tiles
        };

        const json = JSON.stringify(exportData, null, 2);
        this.downloadFile(json, 'tilemap.json', 'application/json');

        if (options.generatePrefab !== false) {
            this._generateUnityPrefabData(exportData);
        }
    }

    /* ------------------------------------------------------------------ */
    /*  UNITY C# IMPORTER (with shadow support)                            */
    /* ------------------------------------------------------------------ */

    _generateUnityPrefabData(tilemapData) {
        this.downloadFile(this._generateUnityImportScript(), 'IsometricTilemapImporter.cs', 'text/plain');
        this.downloadFile(this._generateReadme(), 'UNITY_IMPORT_INSTRUCTIONS.md', 'text/markdown');
    }

    _generateUnityImportScript() {
        return [
'using UnityEngine;',
'using UnityEngine.Rendering;',
'using System.Collections.Generic;',
'using System.IO;',
'',
'/// <summary>',
'/// Imports an isometric tilemap JSON exported from the Isometric 3D Editor.',
'/// Attach this script to an empty GameObject and call ImportTilemap() from',
'/// the Inspector button or from another script.',
'/// </summary>',
'public class IsometricTilemapImporter : MonoBehaviour',
'{',
'    [Header("Import Settings")]',
'    public string jsonFilePath          = "tilemap.json";',
'    public bool   generateColliders     = true;',
'    public bool   createDirectionalLight = true;',
'',
'    // ── Data classes ────────────────────────────────────────────────',
'    [System.Serializable] public class TileData',
'    {',
'        public int    gridX, gridY;',
'        public float  worldY;',
'        public string name, type, layer, spriteName;',
'        public int    zIndex, rotation;',
'        public ScaleData   scale;',
'        public MaterialData material;',
'        public BoundsData  bounds;',
'        public ColliderData collider;',
'        public string shadowCasting;',
'        public bool   receiveShadows;',
'    }',
'    [System.Serializable] public class ScaleData   { public float x,y,z; }',
'    [System.Serializable] public class BoundsData  { public float width,height,depth; }',
    '    [System.Serializable] public class MaterialData',
    '    {',
    '        public string color;',
    '        public float  opacity;',
    '        public bool   transparent;',
'    }',
'    [System.Serializable] public class ColliderData',
'    {',
'        public bool   enabled;',
'        public string type;',
'        public float[] size;',
'    }',
'    [System.Serializable] public class TilemapData',
'    {',
'        public string    version, format;',
'        public SettingsData settings;',
'        public List<TileData> tiles;',
'    }',
'    [System.Serializable] public class SettingsData',
'    {',
'        public CellSize cellSize;',
'        public bool     shadowsEnabled;',
'        public string   colliderType;',
'    }',
'    [System.Serializable] public class CellSize { public float x,y,z; }',
'',
'    // ── Import entry point ───────────────────────────────────────────',
'    [ContextMenu("Import Tilemap")]',
'    public void ImportTilemap()',
'    {',
'        if (!File.Exists(jsonFilePath))',
'        {',
'            Debug.LogError("Tilemap file not found: " + jsonFilePath);',
'            return;',
'        }',
'',
'        string json = File.ReadAllText(jsonFilePath);',
'        TilemapData data = JsonUtility.FromJson<TilemapData>(json);',
'',
'        // Clear any previous import',
'        for (int i = transform.childCount - 1; i >= 0; i--)',
'            DestroyImmediate(transform.GetChild(i).gameObject);',
'',
'        foreach (var tile in data.tiles)',
'            CreateTile(tile, data.settings);',
'',
'        if (createDirectionalLight)',
'            SetupDirectionalLight();',
'',
'        Debug.Log($"Tilemap imported: {data.tiles.Count} tiles");',
'    }',
'',
'    // ── Create one tile ──────────────────────────────────────────────',
'    void CreateTile(TileData td, SettingsData settings)',
'    {',
'        GameObject go = new GameObject(td.name);',
'        go.transform.SetParent(transform);',
'',
'        float cs   = settings.cellSize.x;',
'        float wx   = (td.gridX - td.gridY) * cs * 0.5f;',
'        float wz   = (td.gridX + td.gridY) * cs * 0.5f;',
'        go.transform.position       = new Vector3(wx, td.worldY, wz);',
'        go.transform.rotation       = Quaternion.Euler(0, td.rotation, 0);',
'        go.transform.localScale     = new Vector3(td.scale.x, td.scale.y, td.scale.z);',
'',
'        // Mesh',
'        MeshFilter   mf = go.AddComponent<MeshFilter>();',
'        MeshRenderer mr = go.AddComponent<MeshRenderer>();',
'        mf.sharedMesh   = GetMeshForType(td.type);',
'        mr.sharedMaterial = BuildMaterial(td.material);',
'',
'        // Shadow flags (Stage-1 addition)',
'        mr.shadowCastingMode = td.shadowCasting == "TwoSided"',
'            ? ShadowCastingMode.TwoSided',
'            : ShadowCastingMode.On;',
'        mr.receiveShadows = td.receiveShadows;',
'',
'        // Collider',
'        if (td.collider != null && td.collider.enabled)',
'            AddCollider(go, td);',
'    }',
'',
'    // ── Mesh selection ───────────────────────────────────────────────',
'    Mesh GetMeshForType(string type)',
'    {',
'        switch (type)',
'        {',
'            case "sphere":   return Resources.GetBuiltinResource<Mesh>("New-Sphere.fbx");',
'            case "cylinder": return Resources.GetBuiltinResource<Mesh>("New-Cylinder.fbx");',
'            default:         return Resources.GetBuiltinResource<Mesh>("Cube.fbx");',
'        }',
'    }',
'',
'    // ── Material ─────────────────────────────────────────────────────',
'    Material BuildMaterial(MaterialData md)',
'    {',
'        // Use URP Lit if available, fall back to Standard',
'        Shader shader = Shader.Find("Universal Render Pipeline/Lit")',
'                     ?? Shader.Find("Standard");',
'        Material mat  = new Material(shader);',
'',
'        Color col;',
'        ColorUtility.TryParseHtmlString(md.color, out col);',
'        mat.color = col;',
'',
'        if (md.transparent)',
'',
'        {',
'            mat.SetFloat("_Mode",      3f);',
'            mat.SetInt("_SrcBlend",    (int)BlendMode.SrcAlpha);',
'            mat.SetInt("_DstBlend",    (int)BlendMode.OneMinusSrcAlpha);',
'            mat.SetInt("_ZWrite",      0);',
'            mat.EnableKeyword("_ALPHABLEND_ON");',
'            mat.renderQueue = 3000;',
'            col.a = md.opacity;',
'            mat.color = col;',
'        }',
'',
'        return mat;',
'    }',
'',
'    // ── Collider ─────────────────────────────────────────────────────',
'    void AddCollider(GameObject go, TileData td)',
'    {',
'        if (td.collider.type == "mesh")',
'        {',
'            go.AddComponent<MeshCollider>();',
'        }',
'        else',
'        {',
'            BoxCollider bc = go.AddComponent<BoxCollider>();',
'            if (td.collider.size != null && td.collider.size.Length >= 3)',
'                bc.size = new Vector3(td.collider.size[0],',
'                                      td.collider.size[1],',
'                                      td.collider.size[2]);',
'        }',
'    }',
'',
'    // ── Directional light for real-time shadows ───────────────────────',
'    void SetupDirectionalLight()',
'    {',
'        GameObject lightGO = new GameObject("SceneDirectionalLight");',
'        lightGO.transform.SetParent(transform);',
'',
'        Light light            = lightGO.AddComponent<Light>();',
'        light.type             = LightType.Directional;',
'        light.color            = Color.white;',
'        light.intensity        = 1.2f;',
'        light.shadows          = LightShadows.Soft;',
'        light.shadowStrength   = 0.8f;',
'        light.shadowBias       = 0.02f;',
'        light.shadowNormalBias = 0.1f;',
'        lightGO.transform.rotation = Quaternion.Euler(50f, -30f, 0f);',
'',
'        // Ambient fill',
'        RenderSettings.ambientMode      = UnityEngine.Rendering.AmbientMode.Flat;',
'        RenderSettings.ambientLight     = new Color(0.25f, 0.25f, 0.35f);',
'',
'        Debug.Log("Directional light created. Ensure your Quality Settings have shadow distance >= 50.");',
'    }',
'}'
        ].join('\n');
    }

    _generateReadme() {
        return [
'# Unity Isometric Tilemap Import Guide',
'',
'## Files exported',
'',
'| File | Purpose |',
'|------|---------|',
'| `tilemap.json` | Scene data (tiles, layers, materials, colliders, shadow flags) |',
'| `IsometricTilemapImporter.cs` | C# importer script |',
'| `UNITY_IMPORT_INSTRUCTIONS.md` | This file |',
'',
'## Quick start',
'',
'1. Copy all exported files into your Unity project `Assets/` folder.',
'2. Create an empty GameObject in your scene, name it **IsometricScene**.',
'3. Attach `IsometricTilemapImporter` to it.',
'4. Set **Json File Path** to the location of `tilemap.json` (relative or absolute).',
'5. Right-click the component → **Import Tilemap**.',
'',
'## Real-time shadows',
'',
'The importer automatically:',
'- Sets every mesh to **ShadowCastingMode.TwoSided**.',
'- Sets **receiveShadows = true** on every mesh.',
'- Creates a pre-configured **Directional Light** with Soft Shadows.',
'',
'To tune shadows in Unity:',
'1. Edit → Project Settings → Quality → **Shadow Distance** (set to 50+).',
'2. Select the Directional Light and adjust **Shadow Strength / Bias** if you',
'   see shadow acne or peter-panning.',
'3. For URP: use the **Universal Render Pipeline Asset** and ensure',
'   *Cast Shadows* is enabled on the renderer.',
'',
'## Colliders',
'',
'Box colliders are added by default with sizes matching the exported geometry.',
'Set **Collider Type** to `mesh` in the editor UI for non-box shapes',
'(ramps, roofs, bridges).',
'',
'## Object types supported',
'',
'`cube`, `sphere`, `cylinder`, `ramp`, `terrain`, `wall`, `building`,',
'`path`, `river`, `stairs`, `roof`, `pyramid`, `bridge`',
''
        ].join('\n');
    }

    /* ------------------------------------------------------------------ */
    /*  DOWNLOAD HELPER                                                     */
    /* ------------------------------------------------------------------ */

    downloadFile(content, filename, mimeType) {
        const blob = content instanceof Blob
            ? content
            : new Blob([content], { type: mimeType });

        const url = URL.createObjectURL(blob);
        const a   = document.createElement('a');
        a.href     = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }
}

/* ------------------------------------------------------------------ */
/*  Module exports                                                      */
/* ------------------------------------------------------------------ */

let exportManager = null;

export function initExportManager(scene, objects, layerManager, textureManager) {
    exportManager = new ExportManager(scene, objects, layerManager, textureManager);
    return exportManager;
}

export function getExportManager() {
    return exportManager;
}

export { ExportManager };
